name: test command_line

on:
  push:
  workflow_dispatch:

permissions:
  checks: write
  contents: read
  pull-requests: write
  issues: read

jobs:

  sprint_3:
    runs-on: ubuntu-22.04
    steps:

      - name: Checkout code & tests
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install dependencies
        run: |
          pip uninstall conan -y
          pip install -U conan==1.59.0
          pip install -r requirements.txt
          pip show pytest

      # - name: run tests sprint3 instrumentation
      #   run: |
      #     cd cpp-backend-tests-practicum/scripts/sprint3
      #     ./instrumentation/run.sh

#      - name: Load map_json binary
#        uses: actions/download-artifact@v3
#        with:
#          name: game_server
#          path: ${{ github.workspace }}/sprint1/problems/map_json/solution/build/bin

#      - run: chmod +x ${GITHUB_WORKSPACE}/sprint1/problems/map_json/solution/build/bin/game_server

      # - name: Load FlameGraph
      #   uses: actions/checkout@v3
      #   with:
      #     repository: 'brendangregg/FlameGraph'
      #     path: ${{ github.workspace }}/sprint3/problems/flamegraph/solution/FlameGraph

      # - name: run tests sprint3 flamegraph
      #   run: |
      #     ./cpp-backend-tests-practicum/scripts/sprint1/map_json/build.sh
      #     cd cpp-backend-tests-practicum/scripts/sprint3
      #     ./flamegraph/run.sh

      # - name: run tests sprint3 gen_objects
      #   run: |
      #     cd cpp-backend-tests-practicum/scripts/sprint3
      #     ./gen_objects/run.sh

      # - name: run tests sprint3 static_lib
      #   run: |
      #     cd cpp-backend-tests-practicum/scripts/sprint3
      #     pip show pytest
      #     ./static_lib/run.sh

      - name: run tests sprint3 gather-tests
        run: |
          cd cpp-backend-tests-practicum/scripts/sprint3
          ./gather-tests/run.sh

      - name: run tests sprint3 gather-tests_wrong1
        run: |
          cd cpp-backend-tests-practicum/scripts/sprint3
          ./gather-tests_wrong1/run.sh

      - name: run tests sprint3 gather-tests_wrong2
        run: |
          cd cpp-backend-tests-practicum/scripts/sprint3
          ./gather-tests_wrong2/run.sh

      - name: run tests sprint3 gather-tests_wrong3
        run: |
          cd cpp-backend-tests-practicum/scripts/sprint3
          ./gather-tests_wrong3/run.sh

      - name: run tests sprint3 gather-tests_wrong4
        run: |
          cd cpp-backend-tests-practicum/scripts/sprint3
          ./gather-tests_wrong4/run.sh

      - name: run tests sprint3 gather-tests_wrong5
        run: |
          cd cpp-backend-tests-practicum/scripts/sprint3
          ./gather-tests_wrong5/run.sh

      # - name: run tests sprint3 gather
      #   run: |
      #     cd cpp-backend-tests-practicum/scripts/sprint3
      #     ./gather/run.sh

      # - name: run tests sprint3 find_return
      #   run: |
      #     cd cpp-backend-tests-practicum/scripts/sprint3
      #     ./find_return/run.sh

      # - name: run tests sprint3 scores
      #   run: |
      #     cd cpp-backend-tests-practicum/scripts/sprint3
      #     ./scores/run.sh

      # - name: run tests sprint3 ammo
      #   run: |
      #     cd cpp-backend-tests-practicum/scripts/sprint3
      #     ./ammo/run.sh

      # - name: run tests sprint3 load
      #   run: |
      #     cd cpp-backend-tests-practicum/scripts/sprint3
      #     ./load/run.sh

      - name: Publish XML reports
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          junit_files: ${{ github.workspace }}/*.xml